import os
import datetime

log_directory = "tools/LocalizationUpdater/Logs"
current_time = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
log_filename = os.path.join(log_directory, f"LocalizationUpdate_{current_time}.log")

temp_en_old_directory = "tools/LocalizationUpdater/OldLocale/"
core_en_directory = "translation/en/"
core_pl_directory = "translation/pl/"

en_to_pl_file_pairs = [
    ("en", "pl"),
    ("action-en", "action-pl"),
    ("re-en", "re-pl"),
    ("dictionary", "dictionary"),
    ("kingmaker-en", "kingmaker-pl"),
    ("compendium/action-macros", "compendium/pf2e.action-macros"),
    ("compendium/actions","compendium/pf2e.actionspf2e"),
    ("compendium/adventure-specific-actions","compendium/pf2e.adventure-specific-actions"),
    ("compendium/ancestries","compendium/pf2e.ancestries"),
    ("compendium/ancestryfeatures","compendium/pf2e.ancestryfeatures"),
    ("compendium/backgrounds","compendium/pf2e.backgrounds"),
    ("compendium/bestiary-ability-glossary-srd","compendium/pf2e.bestiary-ability-glossary-srd"),
    ("compendium/bestiary-effects","compendium/pf2e.bestiary-effects"),
    ("compendium/bestiary-family-ability-glossary","compendium/pf2e.bestiary-family-ability-glossary"),
    ("compendium/boons-and-curses","compendium/pf2e.boons-and-curses"),
    ("compendium/campaign-effects","compendium/pf2e.campaign-effects"),
    ("compendium/classes","compendium/pf2e.classes"),
    ("compendium/classfeatures","compendium/pf2e.classfeatures"),
    ("compendium/conditions","compendium/pf2e.conditionitems"),
    ("compendium/criticaldeck","compendium/pf2e.criticaldeck"),
    ("compendium/deities","compendium/pf2e.deities"),
    ("compendium/equipment-effects","compendium/pf2e.equipment-effects"),
    ("compendium/equipment","compendium/pf2e.equipment-srd"),
    ("compendium/familiar-abilities","compendium/pf2e.familiar-abilities"),
    ("compendium/feat-effects","compendium/pf2e.feat-effects"),
    ("compendium/feats","compendium/pf2e.feats-srd"),
    ("compendium/hazards","compendium/pf2e.hazards"),
    ("compendium/heritages","compendium/pf2e.heritages"),
    ("compendium/iconics","compendium/pf2e.iconics"),
    ("compendium/journals","compendium/pf2e.journals"),
    ("compendium/kingmaker-features","compendium/pf2e.kingmaker-features"),
    ("compendium/other-effects","compendium/pf2e.other-effects"),
    ("compendium/paizo-pregens","compendium/pf2e.paizo-pregens"),
    ("compendium/macros","compendium/pf2e.pf2e-macros"),
    ("compendium/rollable-tables","compendium/pf2e.rollable-tables"),
    ("compendium/spell-effects","compendium/pf2e.spell-effects"),
    ("compendium/spells","compendium/pf2e.spells-srd"),
    ("compendium/vehicles","compendium/pf2e.vehicles"),
    ("compendium/abomination-vaults-bestiary","compendium/pf2e.abomination-vaults-bestiary"),
    ("compendium/menace-under-otari-bestiary","compendium/pf2e.menace-under-otari-bestiary"),
    ("compendium/outlaws-of-alkenstar-bestiary","compendium/pf2e.outlaws-of-alkenstar-bestiary"),
    ("compendium/rusthenge-bestiary","compendium/pf2e.rusthenge-bestiary"),
    ("compendium/age-of-ashes-bestiary","compendium/pf2e.age-of-ashes-bestiary"),
    ("compendium/agents-of-edgewatch-bestiary","compendium/pf2e.agents-of-edgewatch-bestiary"),
    ("compendium/blog-bestiary","compendium/pf2e.blog-bestiary"),
    ("compendium/blood-lords-bestiary","compendium/pf2e.blood-lords-bestiary"),
    ("compendium/book-of-the-dead-bestiary","compendium/pf2e.book-of-the-dead-bestiary"),
    ("compendium/crown-of-the-kobold-king-bestiary","compendium/pf2e.crown-of-the-kobold-king-bestiary"),
    ("compendium/extinction-curse-bestiary","compendium/pf2e.extinction-curse-bestiary"),
    ("compendium/fists-of-the-ruby-phoenix-bestiary","compendium/pf2e.fists-of-the-ruby-phoenix-bestiary"),
    ("compendium/gatewalkers-bestiary","compendium/pf2e.gatewalkers-bestiary"),
    ("compendium/kingmaker-bestiary","compendium/pf2e.kingmaker-bestiary"),
    ("compendium/malevolence-bestiary","compendium/pf2e.malevolence-bestiary"),
    ("compendium/mwangi-expanse-bestiary","compendium/pf2e.mwangi-expanse-bestiary"),
    ("compendium/night-of-the-gray-death-bestiary","compendium/pf2e.night-of-the-gray-death-bestiary"),
    ("compendium/one-shot-bestiary","compendium/pf2e.one-shot-bestiary"),
    ("compendium/pathfinder-bestiary","compendium/pf2e.pathfinder-bestiary"),
    ("compendium/pathfinder-bestiary-2","compendium/pf2e.pathfinder-bestiary-2"),
    ("compendium/pathfinder-bestiary-3","compendium/pf2e.pathfinder-bestiary-3"),
    ("compendium/pathfinder-monster-core","compendium/pf2e.pathfinder-monster-core"),
    ("compendium/pfs-introductions-bestiary","compendium/pf2e.pfs-introductions-bestiary"),
    ("compendium/blog-bestiary","compendium/pf2e.blog-bestiary"),
    ("compendium/pfs-season-1-bestiary","compendium/pf2e.pfs-season-1-bestiary"),
    ("compendium/pfs-season-2-bestiary","compendium/pf2e.pfs-season-2-bestiary"),
    ("compendium/pfs-season-3-bestiary","compendium/pf2e.pfs-season-3-bestiary"),
    ("compendium/pfs-season-4-bestiary","compendium/pf2e.pfs-season-4-bestiary"),
    ("compendium/pfs-season-5-bestiary","compendium/pf2e.pfs-season-5-bestiary"),
    ("compendium/rage-of-elements-bestiary","compendium/pf2e.rage-of-elements-bestiary"),
    ("compendium/season-of-ghosts-bestiary","compendium/pf2e.season-of-ghosts-bestiary"),
    ("compendium/shadows-at-sundown-bestiary","compendium/pf2e.shadows-at-sundown-bestiary"),
    ("compendium/sky-kings-tomb-bestiary","compendium/pf2e.sky-kings-tomb-bestiary"),
    ("compendium/stolen-fate-bestiary","compendium/pf2e.stolen-fate-bestiary"),
    ("compendium/strength-of-thousands-bestiary","compendium/pf2e.strength-of-thousands-bestiary"),
    ("compendium/the-enmity-cycle-bestiary","compendium/pf2e.the-enmity-cycle-bestiary"),
    ("compendium/the-slithering-bestiary","compendium/pf2e.the-slithering-bestiary"),
    ("compendium/troubles-in-otari-bestiary","compendium/pf2e.troubles-in-otari-bestiary"),
]
