import os
import datetime

log_directory = "tools/LocalizationUpdater/Logs"
current_time = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
log_filename = os.path.join(log_directory, f"LocalizationUpdate_{current_time}.log")

temp_en_old_directory = "tools/LocalizationUpdater/OldLocale/"
core_en_directory = "translation/en/"
core_pl_directory = "translation/pl/"

en_to_pl_file_pairs = [
    ("en", "pl"),
    ("action-en", "action-pl"),
    ("re-en", "re-pl"),
    ("dictionary", "dictionary"),
    ("kingmaker-en", "kingmaker-pl"),
    ("compendium/_packs-folders", "compendium/pf2e._packs-folders"),
    ("compendium/abomination-vaults-bestiary", "compendium/pf2e.abomination-vaults-bestiary"),
    ("compendium/action-macros", "compendium/pf2e.action-macros"),
    ("compendium/actions", "compendium/pf2e.actionspf2e"),
    ("compendium/adventure-specific-actions", "compendium/pf2e.adventure-specific-actions"),
    ("compendium/age-of-ashes-bestiary", "compendium/pf2e.age-of-ashes-bestiary"),
    ("compendium/agents-of-edgewatch-bestiary", "compendium/pf2e.agents-of-edgewatch-bestiary"),
    ("compendium/ancestries", "compendium/pf2e.ancestries"),
    ("compendium/ancestryfeatures", "compendium/pf2e.ancestryfeatures"),
    ("compendium/backgrounds", "compendium/pf2e.backgrounds"),
    ("compendium/bestiary-ability-glossary-srd", "compendium/pf2e.bestiary-ability-glossary-srd"),
    ("compendium/bestiary-effects", "compendium/pf2e.bestiary-effects"),
    ("compendium/bestiary-family-ability-glossary", "compendium/pf2e.bestiary-family-ability-glossary"),
    ("compendium/blog-bestiary", "compendium/pf2e.blog-bestiary"),
    ("compendium/blood-lords-bestiary", "compendium/pf2e.blood-lords-bestiary"),
    ("compendium/boons-and-curses", "compendium/pf2e.boons-and-curses"),
    ("compendium/book-of-the-dead-bestiary", "compendium/pf2e.book-of-the-dead-bestiary"),
    ("compendium/campaign-effects", "compendium/pf2e.campaign-effects"),
    ("compendium/classes", "compendium/pf2e.classes"),
    ("compendium/classfeatures", "compendium/pf2e.classfeatures"),
    ("compendium/conditions", "compendium/pf2e.conditionitems"),
    ("compendium/crown-of-the-kobold-king-bestiary", "compendium/pf2e.crown-of-the-kobold-king-bestiary"),
    ("compendium/criticaldeck", "compendium/pf2e.criticaldeck"),
    ("compendium/curtain-call-bestiary", "compendium/pf2e.curtain-call-bestiary"),
    ("compendium/deities", "compendium/pf2e.deities"),
    ("compendium/equipment", "compendium/pf2e.equipment-srd"),
    ("compendium/equipment-effects", "compendium/pf2e.equipment-effects"),
    ("compendium/extinction-curse-bestiary", "compendium/pf2e.extinction-curse-bestiary"),
    ("compendium/familiar-abilities", "compendium/pf2e.familiar-abilities"),
    ("compendium/fall-of-plaguestone", "compendium/pf2e.fall-of-plaguestone-bestiary"),
    ("compendium/feat-effects", "compendium/pf2e.feat-effects"),
    ("compendium/feats", "compendium/pf2e.feats-srd"),
    ("compendium/fists-of-the-ruby-phoenix-bestiary", "compendium/pf2e.fists-of-the-ruby-phoenix-bestiary"),
    ("compendium/gatewalkers-bestiary", "compendium/pf2e.gatewalkers-bestiary"),
    ("compendium/heritages", "compendium/pf2e.heritages"),
    ("compendium/highhelm-bestiary", "compendium/pf2e.lost-omens-highhelm-bestiary"),
    ("compendium/hazards", "compendium/pf2e.hazards"),
    ("compendium/iconics", "compendium/pf2e.iconics"),
    ("compendium/journals", "compendium/pf2e.journals"),
    ("compendium/kingmaker-bestiary", "compendium/pf2e.kingmaker-bestiary"),
    ("compendium/kingmaker-features", "compendium/pf2e.kingmaker-features"),
    ("compendium/macros", "compendium/pf2e.pf2e-macros"),
    ("compendium/malevolence-bestiary", "compendium/pf2e.malevolence-bestiary"),
    ("compendium/menace-under-otari-bestiary", "compendium/pf2e.menace-under-otari-bestiary"),
    ("compendium/mwangi-expanse-bestiary", "compendium/pf2e.lost-omens-mwangi-expanse-bestiary"),
    ("compendium/night-of-the-gray-death-bestiary", "compendium/pf2e.night-of-the-gray-death-bestiary"),
    ("compendium/one-shot-bestiary", "compendium/pf2e.one-shot-bestiary"),
    ("compendium/other-effects", "compendium/pf2e.other-effects"),
    ("compendium/outlaws-of-alkenstar-bestiary", "compendium/pf2e.outlaws-of-alkenstar-bestiary"),
    ("compendium/paizo-pregens", "compendium/pf2e.paizo-pregens"),
    ("compendium/pathfinder-bestiary", "compendium/pf2e.pathfinder-bestiary"),
    ("compendium/pathfinder-bestiary-2", "compendium/pf2e.pathfinder-bestiary-2"),
    ("compendium/pathfinder-bestiary-3", "compendium/pf2e.pathfinder-bestiary-3"),
    ("compendium/pathfinder-monster-core", "compendium/pf2e.pathfinder-monster-core"),
    ("compendium/pfs-introductions-bestiary", "compendium/pf2e.pfs-introductions-bestiary"),
    ("compendium/pfs-season-1-bestiary", "compendium/pf2e.pfs-season-1-bestiary"),
    ("compendium/pfs-season-2-bestiary", "compendium/pf2e.pfs-season-2-bestiary"),
    ("compendium/pfs-season-3-bestiary", "compendium/pf2e.pfs-season-3-bestiary"),
    ("compendium/pfs-season-4-bestiary", "compendium/pf2e.pfs-season-4-bestiary"),
    ("compendium/pfs-season-5-bestiary", "compendium/pf2e.pfs-season-5-bestiary"),
    ("compendium/rage-of-elements-bestiary", "compendium/pf2e.rage-of-elements-bestiary"),
    ("compendium/rollable-tables", "compendium/pf2e.rollable-tables"),
    ("compendium/rusthenge-bestiary", "compendium/pf2e.rusthenge-bestiary"),
    ("compendium/season-of-ghosts-bestiary", "compendium/pf2e.season-of-ghosts-bestiary"),
    ("compendium/shadows-at-sundown-bestiary", "compendium/pf2e.shadows-at-sundown-bestiary"),
    ("compendium/sky-kings-tomb-bestiary", "compendium/pf2e.sky-kings-tomb-bestiary"),
    ("compendium/spell-effects", "compendium/pf2e.spell-effects"),
    ("compendium/spells", "compendium/pf2e.spells-srd"),
    ("compendium/stolen-fate-bestiary", "compendium/pf2e.stolen-fate-bestiary"),
    ("compendium/strength-of-thousands-bestiary", "compendium/pf2e.strength-of-thousands-bestiary"),
    ("compendium/the-enmity-cycle-bestiary", "compendium/pf2e.the-enmity-cycle-bestiary"),
    ("compendium/the-slithering-bestiary", "compendium/pf2e.the-slithering-bestiary"),
    ("compendium/troubles-in-otari-bestiary", "compendium/pf2e.troubles-in-otari-bestiary"),
    ("compendium/vehicles", "compendium/pf2e.vehicles"),
    ("compendium/howl-of-the-wild-bestiary", "compendium/pf2e.howl-of-the-wild-bestiary"),
    ("compendium/impossible-lands-bestiary", "compendium/pf2e.lost-omens-impossible-lands-bestiary"),
    ("compendium/monsters-of-myth-bestiary", "compendium/pf2e.lost-omens-monsters-of-myth-bestiary"),
    ("compendium/tian-xia-world-guide-bestiary", "compendium/pf2e.lost-omens-tian-xia-world-guide"),
    ("compendium/travel-guide-bestiary", "compendium/pf2e.lost-omens-travel-guide-bestiary"),
    ("compendium/npc-gallery", "compendium/pf2e.npc-gallery"),
    ("compendium/pathfinder-dark-archive", "compendium/pf2e.pathfinder-dark-archive"),
    ("compendium/pfs-season-6-bestiary", "compendium/pf2e.pfs-season-6-bestiary"),
    ("compendium/prey-for-death-bestiary", "compendium/pf2e.prey-for-death-bestiary"),
    ("compendium/quest-for-the-frozen-flame-bestiary", "compendium/pf2e.quest-for-the-frozen-flame-bestiary"),
    ("compendium/seven-dooms-for-sandpoint-bestiary", "compendium/pf2e.seven-dooms-for-sandpoint-bestiary"),
    ("compendium/wardens-of-wildwood-bestiary", "compendium/pf2e.wardens-of-wildwood-bestiary"),
    ("compendium/pathfinder-society-boons", "compendium/pf2e.pathfinder-society-boons"),
    ("compendium/triumph-of-the-tusk-bestiary", "compendium/pf2e.triumph-of-the-tusk-bestiary"),
    ("compendium/war-of-immortals-bestiary", "compendium/pf2e.war-of-immortals-bestiary"),
    ("compendium/spore-war-bestiary", "compendium/pf2e.spore-war-bestiary"),
    ("compendium/shades-of-blood-bestiary", "compendium/pf2e.shades-of-blood-bestiary"),
    ("compendium/claws-of-the-tyrant-bestiary", "compendium/pf2e.claws-of-the-tyrant-bestiary"),
    ("compendium/lost-omens-bestiary", "compendium/pf2e.lost-omens-bestiary"),
    ("compendium/pathfinder-npc-core", "compendium/pf2e.pathfinder-npc-core"),
]

completed_files = [
    "translation/pl/pl.json",
    "translation/pl/action-pl.json",
    "translation/pl/compendium/pf2e._packs-folders.json",
    "translation/pl/compendium/pf2e.classes.json",
    "translation/pl/compendium/pf2e.conditionitems.json",
    "translation/pl/compendium/pf2e.familiar-abilities.json"
]